server:
  port: 20001
spring:
  flyway.baseline-on-migrate: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/DouglasTV?serverTimezone=America/Bogota
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      limit-param-name: limit
      page-param-name: page
      sort-param-name: sort
      default-page-size: 5
      max-page-size: 10
security:
  key: Este_,vfvijoesfnffnLAwivjoejrbmKeyksjvdeksjvmseguidad