server:
  port: 20001
spring:
  messages:
    basename: messages,config.i18n.messages
  flyway.baseline-on-migrate: true
  datasource:
    username: root
    password: 19871988
    url: jdbc:mysql://seriestv.c6gnqghev7ml.us-east-2.rds.amazonaws.com:3306/seriestv
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      limit-param-name: limit
      page-param-name: page
      sort-param-name: sort
      default-page-size: 5
      max-page-size: 10
security:
  key: Este_,vfvijoesfnffnLAwivjoejrbmKeyksjvdeksjvmseguidad