
spring:
  messages:
    basename: messages,config.i18n.messages
  flyway.baseline-on-migrate: true
  datasource:
    username: root
    password: rootmariadbsql
    url: jdbc:mysql://spring-angular-douglas.ck2qw782xgml.us-east-2.rds.amazonaws.com:3306/DouglasTV?serverTimezone=America/Bogota
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      limit-param-name: limit
      page-param-name: page
      sort-param-name: sort
      default-page-size: 5
      max-page-size: 10
security:
  key: Este_,vfvijoesfnffnLAwivjoejrbmKeyksjvdeksjvmseguidad